STOPWORDS_FR = [
    "a", "à", "au", "aux", "avec", "ce", "ces", "dans", "de", "des", "du", "elle", "en", "et", "eux",
    "il", "ils", "je", "j'ai", "j'", "la", "le", "les", "leur", "lui", "ma", "mais", "me", "même",
    "mes", "moi", "mon", "ni", "notre", "nous", "on", "ou", "par", "pas", "pour", "qu'", "que", "qui",
    "s'", "sa", "se", "si", "son", "sur", "ta", "te", "tes", "toi", "ton", "tu", "un", "une", "vos",
    "votre", "vous", "c'", "c'est", "d'", "d'un", "d'une", "est", "sont", "était", "étaient",
    "comme", "comment", "où", "quand", "pourquoi", "quoi", "dont", "alors", "après", "avant",
    "chez", "dans", "depuis", "derrière", "devant", "entre", "jusque", "jusqu'à", "jusques",
    "malgré", "pendant", "pour", "sans", "sauf", "selon", "sous", "suivant", "vu",
    "y", "afin", "ainsi", "car", "cependant", "donc", "enfin", "ensuite", "lorsque", "mais", "néanmoins",
    "or", "parce", "pourtant", "puis", "puisque", "quoique", "sinon", "tandis",
    "ceci", "cela", "cet", "cette", "celui", "celle", "ceux", "celles", "là", "ici",
    "autre", "autres", "certain", "certaine", "certains", "certaines", "chaque", "maint", "mainte", "maints", "maintes",
    "quelque", "quelques", "plusieurs", "tel", "telle", "tels", "telles", "tout", "toute", "tous", "toutes",
    "beaucoup", "peu", "plus", "moins", "tant", "tellement", "très", "trop", "assez",
    "encore", "déjà", "jamais", "maintenant", "toujours", "désormais", "parfois", "souvent",
    "avoir", "être", "faire", "dire", "aller", "voir", "pouvoir", "vouloir", "croire", "savoir", "devoir",
    "falloir", "valoir", "aimer", "appeler", "attendre", "comprendre", "connaître", "continuer", "demander", "donner",
    "ah", "eh", "oh", "ha", "hé", "hein", "ben", "eh bien", "hum", "ok",
] 